name: Format Check

on:
  push:
  pull_request:

jobs:
  prettier:
    name: 📰 Prettier check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"
      - name: Install dependencies
        run: npm install prettier
      - name: Run Prettier check
        run: npx prettier --check .
